### ISSUE TITLE
Cannot unroll the circuit to the given basis, ['u1', 'u2', 'u3', 'rz', 'sx', 'x', 'cx', 'id', 'unitary']

### ISSUE THREAD

**Issue by Next-di-mension** [qiskit-community/qiskit-machine-learning#655]
While using `RawFeatureVector()` as a feature map, I am getting the following error when I try to call `VQC.fit()`: 

`Cannot unroll the circuit to the given basis, ['u1', 'u2', 'u3', 'rz', 'sx', 'x', 'cx', 'id', 'unitary']. Instruction ParameterizedInitialize not found in equivalence library and no rule found to expand.`

Can somebody help me with this?

**Comment by adekusar-drl** [comment]
It is incompatible with the transpiler until all parameters are bound.

`RawFeatureVector` introduces a placeholder for parameters and this placeholder can't be transpiled since the parameters are not bound at the transpilation time. This is a limitation of the state preparation algorithm, it works only when all state parameters are defined. So, what is happening internally: `VQC` passes a parameterized circuit that consists of a feature map and an ansatz to Sampler along with an array of parameters. Sampler tries to transpile the circuit (and here the problem is), bind the parameters and then execute the transpiled circuit as many times as the number of samples in the dataset. At this moment parameters are being bound to the transpiled circuit, so after that the state preparation algorithm should have been executed. But it was invoked earlier, at the transpilation time, when the circuit should have been defined completely. Apparently, `RawFeatureVector` is compatible with the Qiskit primitives only when transpilation is not required.

There's no a simple solution here. A new state preparation algorithm is required for amplitude encoding that is based on parameterized circuits. And let's put aside inefficiency of such an algorithm.

**Comment by Next-di-mension** [comment]
So can I use Sampler separately? and rather than directly passing it to the VQC, can I train the model with some different library, say PyTorch?

**Comment by adekusar-drl** [comment]
If you pass a fully bound circuit to Sampler, then it will work.
