### ISSUE TITLE
Help on QSVC

### ISSUE THREAD

**Issue by gcattan** [qiskit-community/qiskit-machine-learning#721]
hi, this issue is more about asking for help than reporting a real bug. 

In short, we ran an experiment in May 2022 with QSVC + ZZFeatureMap on real data + simulator. We obtained a nice result, with an ROC-AUC of about 0.75.

About a month ago, after updating the requirement and switching to qiskit_aer we re-ran the experiment (same data). The QSVC seems overfitted with ROC-AUC=0.5 and training accuracy = 100%. 

Switching the simulator back, or playing with the regularization (C = 10^-7 -> 10^7) did not help. 

Are you aware of any default parameters or configurations that may have changed during this lap of time? Or, in general, what do you recommend?

**Comment by adekusar-drl** [comment]
Hello, the codebase has gone through quite significant changes since May 2022. We have switched from `QuantumInstance` to primitives, dropped Opflow, replaced QNNs and kernels, a lot of classes have been deprecated and removed. In general, the algorithms are still the same, interfaces can be a bit different. So, if you don't have every single parameter set, then there may be some changes in the results. But changes should not lead to drastically different results.

**Comment by gcattan** [comment]
Thank you for your answer! I have just checked with FidelityStatevectorKernel with the same results. As for the parameter, I have C and max_iter set. Is there any other parameter that I should consider investigating for binary classification with a quantum kernel?

**Comment by adekusar-drl** [comment]
I'd take a look at how circuits are executed. What kind of simulator has been used, its setting and so on.

**Comment by gcattan** [comment]
Thank you for the tips. After breaking down the different elements, I am now confident that the difference comes from the refactoring of the BlueprintCircuit inside Qiskit. It looks like QSVC and the simulator are running as expected.
Thanks!
