### ISSUE TITLE
How to merge custom quantum circuit with quantum machine learning model circuit?

### ISSUE THREAD

**Issue by Herutriana44** [qiskit-community/qiskit-machine-learning#777]
any there how to merge custom quantum circuit with quantum machine learning model circuit? i make custom quantum circuit ,for example, this circuit has 3 qubits, 2 qubits as feature for qml circuit and 1 qubits for prediction result from qml circuit. and if this possible, how to training this qml model? Does the dataset have to be in the form of a quantum circuit? make a simple code example or you can tell me keywords for search about this

**Comment by FrancescaSchiav** [comment]
Hi @Herutriana44, I am having trouble understanding your question fully, regardless, this space is meant more for reporting bug issues and fix or enhancement requests, rather than a prompt for some quick code or keywords to help you search. I will point you to a tutorial you might find helpful, but you might find it useful to also explore the whole library of tutorials you can see in the link below:
https://qiskit-community.github.io/qiskit-machine-learning/tutorials/02a_training_a_quantum_model_on_a_real_dataset.html

You may also want to join the Qiskit Slack community to get support in building your custom circuit: 
https://qisk.it/join-slack

**Comment by Herutriana44** [comment]
> Hi @Herutriana44, I am having trouble understanding your question fully, regardless, this space is meant more for reporting bug issues and fix or enhancement requests, rather than a prompt for some quick code or keywords to help you search. I will point you to a tutorial you might find helpful, but you might find it useful to also explore the whole library of tutorials you can see in the link below: https://qiskit-community.github.io/qiskit-machine-learning/tutorials/02a_training_a_quantum_model_on_a_real_dataset.html
> 
> You may also want to join the Qiskit Slack community to get support in building your custom circuit: https://qisk.it/join-slack

Okay, i Will try it, thanks for your solutions
