### ISSUE TITLE
FidelityQuantumKernel with SamplerV2 (NoiseModel)

### ISSUE THREAD

**Issue by luib01** [qiskit-community/qiskit-machine-learning#852]
### What should we add?

I would like to know if there is the possibility to simulate the noise not from the shots but from a noisemodel of a real backend

**Comment by oscar-wallis** [comment]
You definitely can already, so the new 0.8 release makes it so that we now support Sampler and Estimator V2s, though we admit, that the documentation isn't where it needs to be right now. So you'll need to use FidelityQuantumKernel (as FidelityStatevectorKernel is a pure statevector implementation) with computeuncompute and a SamplerV2 and you're off to the races. As to how you want to introduce your noise that's up to you, either checkout something like GenericBackend or runtime fake_providers or qiskit_aer with a NoiseModel. 
## **Keep in Mind**
You pass your virtual circuit and a custom ComputeUncompute fidelity to the FidelityQuantumKernel. The ComputeUncompute needs the SamplerV2 with whatever run options you wanted, a num_virtual_qubits (the number of qubits in your virtual circuit pre-transpilation) and pass_manager, the pass_manager you would like to use to transpile your circuit onto your backend. I am gonna close the issue with this message but feel free to re-open with any problems your have!

**Comment by luib01** [comment]
thanks for the fast replay. actually i tried it but i get this error, The sampler should be an instance of BaseSampler, but got <class 'qiskit_ibm_runtime.sampler.SamplerV2'> .
  # Create an empty noise model
        noise_model = NoiseModel.from_backend(self.backend)
        
        
        self.composed_circuit=self.qcircuit.compose(self.feature_map,inplace=False)
        #self.composed_circuit=insert_noise(self.composed_circuit,noise_model=noise_model)
        transpiler= generate_preset_pass_manager(backend=self.backend, optimization_level=1)
        transpiled=transpiler.run(self.composed_circuit)
        
        print("Noise model inserted form: "+self.backend.name)
        #self.job=self.backend.run(transpiled)
        sampler=Sampler(self.backend)
        fidelity=ComputeUncompute(sampler=sampler)
        print('Quantum Circuit:')
        print(self.qcircuit)
        print('FEATURE MAP:')
        print(self.composed_circuit)
       
        kernel=FidelityQuantumKernel(feature_map=transpiled,fidelity=fidelity,evaluate_duplicates='all')
thi is the code. the importation are the following. 
from qiskit_ibm_runtime import QiskitRuntimeService, Session, SamplerV2 as Sampler
from qiskit_machine_learning.kernels import FidelityQuantumKernel,BaseKernel
from qiskit_algorithms.state_fidelities import ComputeUncompute

**Comment by oscar-wallis** [comment]
Hi, you need to import ComputeUncompute from qiskit_machine_learning, we have absorbed pieces of qiskit algorithms as this is no longer being maintained. Additionally, when you do use ComputeUncompute make sure you follow the **Keep in Mind** steps above.

**Comment by luib01** [comment]
ok thank you, now it works but is really slow due to the fact that use the fidelity Fidelityquantumkernel and the complexity is O(N^2),while for FidelityStatevectorKernel is O(N). there is any possibility to speed up the computation or add the noise to FidelityStatevectorKernel?

**Comment by oscar-wallis** [comment]
Hi, What backend are you using? I'd recommend using aer, but in general I don't think you can speed up as these are complexity issues, also as there is noise in the system, there will be sampling overhead.

**Comment by oscar-wallis** [comment]
Hi, that looks like a runtime error, not a qiskit machine learning error. I have no idea why it's not running. However, considering brisbane is a 127 qubit QPU, I would imagine that you would not be able to simulate this circuit, depends on your circuit length and depth and your pc memory and cores. For my M2 Pro chip, I can simulate something like 25-30 qubits (though very slowly) using statevector and up to 60-70 qubits on MPS for very shallow circuits, but the deeper your circuit gets the more memory MPS eats up due to the higher bond dimension required.

**Comment by oscar-wallis** [comment]
It is worth keeping in mind, that virtual fidelity circuits are twice the depth of the inputted virtual circuit.

**Comment by luib01** [comment]
So I think it is impossible to simulate my circuit both on aersimulator and the real backend but with the statevector the evaluation is quite fast, I think that I will use it and maybe try to put the noise model into the circuit with the function insert_noise and transpile it before giving it to the statevectorkernel. What do you think?

**Comment by oscar-wallis** [comment]
I'm surprised that you have a circuit that can be run on FidelityStatevectorKernel that can't be run using the aer_sim in the statevector mode, which intuitively seems infeasible. As to your method, if it works great, I haven't used that function before but it will be adding noise via gates which is a normal way to go about it, yeah sure go for it.

**Comment by luib01** [comment]
Thanks for the help.
