### ISSUE TITLE
EstimatorQNN mismatch between installed ML 0.8.0 and its GitHub version

### ISSUE THREAD

**Issue by ironfrown** [qiskit-community/qiskit-machine-learning#873]
### Environment

- **0.8.0**:
- **3.1.10**: 
- **Ubuntu 22.04.5 LTS**: 

### What is happening?

ML 0.8.0 EstimatorQNN with V2 primitives does not accept pass_manager option, but the sources on GitHub allow this (instead an old num_virtual_qubits is being accepted).

### How can we reproduce the issue?

Install ML 0.8.0, create a simple circuit, call EstimatorQNN with V2 estimator and option: pass_manager and/or num_virtual_qubits

### What should happen?

Installed and GitHub versions should be consistent

**Comment by edoaltamura** [comment]
Hi @ironfrown, the mismatch appears to be related to https://github.com/qiskit-community/qiskit-machine-learning/issues/866.

Both these issues are scheduled to be fixed in `v.0.8.1`, expected for this week. I propose keeping this issue open until the release.

For reference, the new `EstimatorQNN` implementation was updated in https://github.com/qiskit-community/qiskit-machine-learning/pull/855 and https://github.com/qiskit-community/qiskit-machine-learning/pull/870.

**Comment by edoaltamura** [comment]
Does this issue persist in version `0.8.1` @ironfrown?

**Comment by edoaltamura** [comment]
The mismatch was resolved in version 0.8.1, and

> ML 0.8.0 EstimatorQNN with V2 primitives does not accept pass_manager option, but the sources on GitHub allow this (instead an old num_virtual_qubits is being accepted).

was fixed in https://github.com/qiskit-community/qiskit-machine-learning/pull/870.
